# Generated by Django 6.1.1 on 2026-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
