# Generated by Django 6.1.1 on 2026-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
