# Generated by Django 6.1.1 on 2026-09-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='Example of discription', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
            preserve_default=False,
        ),
    ]
