# Generated by Django 6.1.1 on 2026-09-21 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_user_bids_remove_user_user_id_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('None', 'No_category'), ('electronics', 'Electronics'), ('books', 'Books'), ('fashion', 'Fashion')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQloBQfR1oxndVS2Z3qfCtzcpFea_-55X9idaGUSIpAQ&s=10', max_length=300),
        ),
        migrations.AlterField(
            model_name='listings',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Createdby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auctions.listings')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('sold_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='auctions.listings')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
