# Generated by Django 6.1.1 on 2026-09-17 08:43

import auctions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_user_bids_remove_user_user_id_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Categories',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='Createdby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=auctions.models.User, max_length=60)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auctions.listings')),
            ],
        ),
    ]
