# Generated by Django 6.1.1 on 2026-09-25 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_category_alter_listings_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.AlterField(
            model_name='sold',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold', to=settings.AUTH_USER_MODEL),
        ),
    ]
