# Generated by Django 6.1.1 on 2026-09-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_categories_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdby',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auctions.listings', unique=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQloBQfR1oxndVS2Z3qfCtzcpFea_-55X9idaGUSIpAQ&s=10', max_length=300),
        ),
        migrations.AlterField(
            model_name='listings',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
