# Generated by Django 6.1.1 on 2026-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_createdby_listing_alter_listings_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='Categories',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('None', 'No_category'), ('electronics', 'Electronics'), ('books', 'Books'), ('fashion', 'Fashion')], default='None', max_length=20),
            preserve_default=False,
        ),
    ]
