# Generated by Django 6.1.1 on 2026-09-25 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_listings_listing_alter_sold_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest', to=settings.AUTH_USER_MODEL),
        ),
    ]
