# Generated by Django 6.1.1 on 2026-09-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdby',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auctions.listing'),
        ),
    ]
